name: us_congress_vote_tracker
description: Keep up with US Congressional activity.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.7.2+161 # REACTIVATED DBASE HASHTAGS LIST, GITHUB NOTIFICATIONS CODE UPDATE

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^2.1.0
  connectivity_plus: ^2.3.9
  convert: ^3.1.1
  crypto: ^3.0.2
  background_fetch: ^1.1.2
  device_info_plus: ^6.0.0
  device_info_plus_platform_interface: ^5.0.0
  dio: ^4.0.6
  dart_twitter_api: ^0.5.6+1
  email_validator: ^2.1.17
  ffi: ^2.0.1
  flutter_dotenv: ^5.0.2
  flutter_linkify: ^5.0.2
  flutter_lints: ^2.0.1
  flutter_local_notifications: ^12.0.2
  font_awesome_flutter: ^10.2.1
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  geolocator_windows: ^0.1.1
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0 # local database helper
  http: ^0.13.5
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  logger: ^1.1.0 # debug logger
  nonce: ^1.2.0
  package_info_plus: ^2.0.0
  path: ^1.8.2
  purchases_flutter: ^4.3.0
  rxdart: ^0.27.5
  share_plus: ^5.0.0
  url_launcher: ^6.1.6
  webview_flutter: ^3.0.4
  youtube_player_flutter: ^8.1.1
  youtube_player_iframe: ^3.1.0
#  flutter_gen: ^5.1.0+1

# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.
# cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/capitol_babble_bg.png
    - assets/intro_background.png
    - assets/congress_pic_1.jpg
    - assets/congress_pic_0.png
    - assets/congress_pic_1.png
    - assets/congress_pic_2.png
    - assets/congress_pic_3.png
    - assets/congress_pic_4.png
    - assets/lobbying0.png
    - assets/lobbying1.png
    - assets/travel0.png
    - assets/travel1.png
    - assets/stock0.png
    - assets/stock1.png
    - assets/stock2.png
#    - assets/watchtower.png
    - assets/watchtower_icon.png
    - assets/app_icon.png
    - assets/app_icon_gray.png
    - assets/app_icon_round.png
    - assets/app_icon_tower.png
    - assets/github.png
    - assets/twitter.png
#    - assets/instagram.png
    - assets/google_play_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
